config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    collection do
      get 'myposts'
    end
  end
  get 'pages/index'
  get 'pages/admin'
  get 'pages/manager'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # resources :users do
  #   resources :posts
  # end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "pages#index"

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :role, inclusion: { in: %w(admin editor leader participant),
  message: "%{value} is not a valid role" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit

    before_action :configure_permitted_parameters, if: :devise_controller?

    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
    
    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up) do |user_params|
            user_params.permit(:role, :email, :password, :password_confirmation)
        end
    end

    private

    def user_not_authorized
        flash[:alert] = "You are not authorized to perform this action."
        redirect_to(request.referrer || root_path)
    end
end




  

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!
  def index
    @page_title = "How to use this demo"
  end

  def admin
  end

  def manager
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  def myposts
    @page_title = "My Posts"
    @posts = Post.where(user_id: current_user.id).order(updated_at: :desc)
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    @post = Post.find(params[:id])
    authorize @post
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    authorize @post
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :subtitle, :user_id, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

# This helps to set the active class for Bootstrap menus
    def current_class?(test_path)
        return 'active' if request.path == test_path
        ''
    end
      
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title || "Authorization Demo" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="icon" type="image/png" href="/auth_demo_favicon.png">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render "/shared/navbar" %>
      <%= render "/shared/alert_block" %>
      <div class="container-fluid">
        
        <%= yield %>
      </div>
      
  </body>
</html>

app/views/pages/admin.html.erb
<h1>Pages#admin</h1>
<p>Only Admins can see this page.</p>

app/views/pages/index.html.erb
<h1>How to Use This Authorization Demo</h1>
<p>This web app has been created to demonstrate the use of the <%= link_to 'Devise gem', "https://github.com/heartcombo/devise" %> to authenticate users, and the <%= link_to 'Pundit gem', "https://github.com/varvet/pundit" %> to authorize users to see certain content or take certain
actions based upon defined policies.</p>

<p>There are six accounts created for the demo, each having one of the four types of roles defined in this application.</p>
<ul>
    <li>Admin email: admin@example.com password: password</li>
    <li>Editor email: editor@example.com password: password</li>
    <li>Leader email: leader@example.com password: password</li>
    <li>Participant email: user1@example.com password: password</li>
    <li>Participant email: user1@example.com password: password</li>
    <li>Participant email: user1@example.com password: password</li>
</ul>

<p>To demonstrate the various levels of access, follow the step by step instructions below:</p>
<ol>
    <li>Log in as "user1@example.com" and navigate to Posts.</li>
    <li>Create a new post and submit.</li>
    <li>Show the new post you created. Note that there is an edit button. That functionality is available to the Admin and Leader roles and also to the owner of the post.</li>
    <li>Now log out. Log in again, but this time as user2@example.com</li>
    <li>Find the Post you just created as user1@example.com. Notice that the edit link is not visible.</li>
    <li>Try to change the URL in the browser by appending the current url of the post with "/edit" to access the update action.</li>
    <li>The form now shows on screen. Try to make a change to the title or subtitle of the Post. Click the "Update" button. Notice that there is an alert saying "You are not authorized to perform this action."</li>
</ol>

<p>Notice that we hid the Update button from unauthorized users (though this does not require Pundit authorization). However, even if the user tries to circumvent
this by adding in the appropriate RESTful action, they are blocked programmatically at the controller level by Pundit policies
configured in the application.</p>

<ol>
    <li>Log out.</li>
    <li>Log back in but this time as an editor or admin.</li>
    <li>Look at the post created above. Notice that the edit button is now available.</li>
    <li>Make a change in the form to the title or subtitle and click Update.</li>
    <li>Now you receive a success notice because a change was made by an authorized user as per Pundit policies we configured.</li>
    <li>Log out</li>
</ol>

<p>Next we want to demonstrate that we can block the ability of certain users from destroying a Post. We want the creator of the post to 
be able to destroy it. And we see a need for an admin to destroy a post a user creates due to objectionable content, but we may not want
give that permission to an editor. So we have configured our Pundit policy to allow the admin role to destroy Posts and also the
creator of the post, but not anyone else.</p>

<ol>
    <li>Log in as user1@example.com</li>
    <li>Create 3 posts</li>
    <li>Go to <%= link_to 'Posts', posts_path %> page to see the 3 posts just created. Click on destroy next to one of them. Notice
    user1@example.com is able to destroy the post. Now log out.</li>
    <li>Log in as editor@example.com.</li>
    <li>Go to <%= link_to 'Posts', posts_path %> page. Click on destroy next to one of the posts. Notice that you receive an alert saying "You are not authorized to perform this action."</li>
    <li>Log out.</li>
    <li>Log in as admin@example.com</li>
    <li>Go to <%= link_to 'Posts', posts_path %> page. Click on destroy next to one of the posts. Notice that you are successful in destroying the post because you are authorized to do so.</li>
</ol>

app/views/pages/manager.html.erb
<h1>Pages#manager</h1>
<p>Find me in app/views/pages/manager.html.erb</p>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>
  <%= form.hidden_field :user_id, :value => current_user.id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Subtitle</th>
      <th>User</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.subtitle %></td>
        <td><%= post.user.email %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/myposts.html.erb
<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Subtitle</th>
      <th>User</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.subtitle %></td>
        <td><%= post.user.email %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Subtitle:</strong>
  <%= @post.subtitle %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.email %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<% if current_user.role == "admin" || current_user.role == "editor" || current_user.id == @post.user_id %>
  <%= link_to 'Edit', edit_post_path(@post) %> |
<% end %>
<%= link_to 'Back', posts_path %>

app/views/shared/_alert_block.html.erb
    <% if notice %>
        <div class="alert alert-success" role="alert">
            <p class="notice"><%= notice %></p>
        </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-danger" role="alert">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="/">Authorization Demo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse container-fluid" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <% if user_signed_in? %>
      <li class="nav-item"><%= link_to 'How to use this Demo', pages_index_path, class: "nav-link #{current_class?(pages_index_path)}" %>
      <li class="nav-item"><%= link_to "Posts", posts_path, class: "nav-link #{current_class?(posts_path)}" %></li>
      <li class="nav-item"><%= link_to "My Posts", myposts_posts_path, class: "nav-link #{current_class?(myposts_posts_path)}" %></li>
    <% end %>
      <!-- Login Items -->
      <li class="nav-item">
        <% if current_user.is_a?(User) %>
          <%= link_to "Log Out", destroy_user_session_path, class: "nav-link" %>
        <% else %>
          <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
        <% end %>
      </li>
    </ul>
    
    <!-- Display name of current_user -->
    <div class="justify-content-end pe-3">
      <% if user_signed_in? %>
        <span class="navbar-text pe-3">Welcome, <%= current_user.email %>!</span>
        <span class="navbar-text pe-3">Your role is: <%= current_user.role %></span>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_testnavbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar w/ text</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse container-fluid" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
    </ul>
    <span class="navbar-text">
      Navbar text with an inline element
    </span>
  </div>
</nav>